# ASSIGNMENT

1. Write a NumPy program and find the product of 2-dim arrays and a 3-dim Array
2. Do a simple calculation using: Sin, Cos, Tan, Log
3. Write a NumPy program to multiply a 5x3 matrix using Matmul
4. Write a NumPy program to create a 3x3 identity matrix
5. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
6. Write a NumPy program to create a new shape to an array without changing its data(for example a 3X2 matrix to a 2x3 matrix)

1. Write a NumPy program and find the product of 2-dim arrays and a 3-dim Array

In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
a.ndim

2

In [5]:
b = np.arange(24) .reshape (2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
b.ndim

3

In [7]:
a.dot(b)

array([[[ 20,  23,  26,  29],
        [ 56,  59,  62,  65]],

       [[ 56,  68,  80,  92],
        [200, 212, 224, 236]],

       [[ 92, 113, 134, 155],
        [344, 365, 386, 407]]])

2. Do a simple calculation using: Sin, Cos, Tan, Log

In [8]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [9]:
np.cos(b)


array([[[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
        [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]],

       [[ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
        [-0.95765948, -0.27516334,  0.66031671,  0.98870462],
        [ 0.40808206, -0.54772926, -0.99996083, -0.53283302]]])

In [10]:
np.tan(a)

array([[ 0.        ,  1.55740772, -2.18503986],
       [-0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146]])

In [11]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [12]:
np.log(50)

3.912023005428146

3. Write a NumPy program to multiply a 5x3 matrix using Matmul

In [13]:
m = np.arange(15).reshape(3,5)

In [14]:
l = np.arange(15).reshape(5,3)

In [15]:
print('M * L = \n', np.matmul(m,l))

M * L = 
 [[ 90 100 110]
 [240 275 310]
 [390 450 510]]


4. Write a NumPy program to create a 3x3 identity matrix

In [16]:
np.full((3,3), 40)

array([[40, 40, 40],
       [40, 40, 40],
       [40, 40, 40]])

5. write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [17]:
c = np.arange(2,11) .reshape(3,3)
print(c)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


6. Write a NumPy program to create a new shape to an array without changing its data(for example a 3X2 matrix to a 2x3 matrix)

In [18]:
d = np.arange(6) .reshape(2,3)

In [19]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
d.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])